version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
    - 5433:5432
    expose: 
    - 5432
    environment:
    - POSTGRES_USER=pathfinder
    - POSTGRES_PASSWORD=pathfinder
    volumes:
    - db:/var/lib/postgresql/data
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/cache/data
  
volumes:
  db:
    driver: local
  redis:
    driver: local
networks:
  default:
    name: pathfinder

